const DirectAnswer = [
    { id: 1, text: "Yes" },
    { id: 2, text: "No" },
    { id: 3, text: "Not now" },
    { id: 4, text: "Wait" },
    { id: 5, text: "Be patient" },
    { id: 6, text: "Let it go" },
    { id: 7, text: "Move forward" },
    { id: 8, text: "Observe first" },
    { id: 9, text: "Trust the process" },
    { id: 10, text: "Act with courage" }
];


const KrishnaGuidance = [
    { "id": 1, "text": "Focus on your duty, not the reward." },
    { "id": 2, "text": "Action with a calm mind brings clarity." },
    { "id": 3, "text": "Do what must be done without fear." },
    { "id": 4, "text": "The restless mind clouds good judgment." },
    { "id": 5, "text": "Detach from outcomes and act sincerely." },
    { "id": 6, "text": "Courage grows when you act despite doubt." },
    { "id": 7, "text": "The path becomes clear when you begin walking." },
    { "id": 8, "text": "A disciplined mind sees truth more easily." },
    { "id": 9, "text": "Peace comes from mastering your thoughts." },
    { "id": 10, "text": "Act according to your true nature." },

    { "id": 11, "text": "When confused, return to your duty." },
    { "id": 12, "text": "Let your actions be pure, not driven by fear." },
    { "id": 13, "text": "Patience reveals the right path." },
    { "id": 14, "text": "Doubt weakens action." },
    { "id": 15, "text": "Steady effort overcomes uncertainty." },
    { "id": 16, "text": "The wise act without attachment." },
    { "id": 17, "text": "Control the mind, and life becomes clearer." },
    { "id": 18, "text": "What must happen will unfold in time." },
    { "id": 19, "text": "A calm mind sees what others miss." },
    { "id": 20, "text": "Truth reveals itself to the patient." },

    { "id": 21, "text": "Fear fades when purpose becomes clear." },
    { "id": 22, "text": "The mind becomes your friend when disciplined." },
    { "id": 23, "text": "Attachment creates suffering." },
    { "id": 24, "text": "Action guided by wisdom brings peace." },
    { "id": 25, "text": "Do not delay what is right." },
    { "id": 26, "text": "Even small steps forward matter." },
    { "id": 27, "text": "A focused mind cannot be shaken." },
    { "id": 28, "text": "Clarity grows through action." },
    { "id": 29, "text": "The present moment holds your duty." },
    { "id": 30, "text": "Let wisdom guide your decisions." },

    { "id": 31, "text": "Balance brings strength." },
    { "id": 32, "text": "Calm the mind before choosing." },
    { "id": 33, "text": "The right action rarely comes from fear." },
    { "id": 34, "text": "Patience protects wise decisions." },
    { "id": 35, "text": "Discipline shapes destiny." },
    { "id": 36, "text": "Focus on effort, not outcome." },
    { "id": 37, "text": "The soul remains steady beyond success or failure." },
    { "id": 38, "text": "Act with sincerity." },
    { "id": 39, "text": "Peace grows in a steady mind." },
    { "id": 40, "text": "Wisdom begins with self-control." },

    { "id": 41, "text": "Do what is right, even when it is difficult." },
    { "id": 42, "text": "The wise are not shaken by praise or blame." },
    { "id": 43, "text": "A restless mind creates confusion." },
    { "id": 44, "text": "Inner strength grows through discipline." },
    { "id": 45, "text": "Let your actions reflect truth." },
    { "id": 46, "text": "Stillness reveals insight." },
    { "id": 47, "text": "Purpose gives courage." },
    { "id": 48, "text": "Clarity appears when attachment fades." },
    { "id": 49, "text": "Choose action over hesitation." },
    { "id": 50, "text": "Your duty is the path forward." },

    { "id": 51, "text": "Let wisdom guide emotion." },
    { "id": 52, "text": "A calm heart sees clearly." },
    { "id": 53, "text": "The mind must be trained like a warrior." },
    { "id": 54, "text": "Act without fear of failure." },
    { "id": 55, "text": "Strength grows through responsibility." },
    { "id": 56, "text": "Detach from praise and criticism." },
    { "id": 57, "text": "A steady mind leads to wise choices." },
    { "id": 58, "text": "Right action brings inner peace." },
    { "id": 59, "text": "Focus on what you can control." },
    { "id": 60, "text": "The present moment asks for action." },

    { "id": 61, "text": "Wisdom grows in silence." },
    { "id": 62, "text": "Clarity follows patience." },
    { "id": 63, "text": "Discipline removes confusion." },
    { "id": 64, "text": "Act without attachment." },
    { "id": 65, "text": "The wise stay steady in uncertainty." },
    { "id": 66, "text": "A focused mind overcomes obstacles." },
    { "id": 67, "text": "Purpose makes the path visible." },
    { "id": 68, "text": "Let truth guide your steps." },
    { "id": 69, "text": "Fear fades when you face your duty." },
    { "id": 70, "text": "A clear mind makes strong decisions." },

    { "id": 71, "text": "Do not let doubt rule your mind." },
    { "id": 72, "text": "Inner calm reveals the right action." },
    { "id": 73, "text": "Wisdom grows through reflection." },
    { "id": 74, "text": "Act steadily and without haste." },
    { "id": 75, "text": "Your actions shape your future." },
    { "id": 76, "text": "Balance emotion with wisdom." },
    { "id": 77, "text": "Let courage lead your steps." },
    { "id": 78, "text": "Clarity appears in disciplined minds." },
    { "id": 79, "text": "Peace belongs to the self-controlled." },
    { "id": 80, "text": "Do your duty with sincerity." },

    { "id": 81, "text": "The wise act without hesitation." },
    { "id": 82, "text": "A calm mind is powerful." },
    { "id": 83, "text": "Right action removes confusion." },
    { "id": 84, "text": "Let patience guide you." },
    { "id": 85, "text": "Your path becomes clear through effort." },
    { "id": 86, "text": "Detach from results." },
    { "id": 87, "text": "Discipline reveals truth." },
    { "id": 88, "text": "Inner strength leads to clarity." },
    { "id": 89, "text": "Choose action with wisdom." },
    { "id": 90, "text": "Balance thought and action." },

    { "id": 91, "text": "Calm your mind before acting." },
    { "id": 92, "text": "Fear fades in the presence of purpose." },
    { "id": 93, "text": "A wise mind remains steady." },
    { "id": 94, "text": "Act with integrity." },
    { "id": 95, "text": "Let discipline guide your life." },
    { "id": 96, "text": "Clarity comes from patience and effort." },
    { "id": 97, "text": "Focus on what is right." },
    { "id": 98, "text": "Peace grows in self-control." },
    { "id": 99, "text": "A focused mind conquers doubt." },
    { "id": 100, "text": "Trust the path revealed through duty." }

];